# fly.toml app configuration file generated for n8n-on-fly-morning-leaf-9187 on 2025-12-13T16:27:20-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'n8n-on-fly-morning-leaf-9187'
primary_region = 'sjc'

[build]
  dockerfile = 'Dockerfile'

[http_service]
  internal_port = 5678
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1

[[services]]
  internal_port = 5678
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

[checks]
  [checks.http]
    port = 5678
    type = 'http'
    interval = '15s'
    timeout = '5s'
    grace_period = '30s'
    path = '/'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024

[[mounts]]
source = "n8n_data"
destination = "/home/node/.n8n"

[env]
  N8N_HOST=n8n-on-fly-morning-leaf-9187.fly.dev
  N8N_PORT=5678
  N8N_PROTOCOL=https
  WEBHOOK_TUNNEL_URL=https://n8n-on-fly-morning-leaf-9187.fly.dev
